AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: >-
  Lambda Function used to perform searches in log files (CS441 - Homework 3)
Resources:
  LogFinderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: LogFinder
      Description: LogFinder
      Runtime: java8
      Handler: lambda.ApiGatewayProxyHandler
      CodeUri: target/scala-3.0.2/LogFinderLambda.jar
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          env: staging
      Events:
        LogFinder:
          Type: Api
          Properties:
            Path: /logfinder
            Method: GET
            RequestParameters:
              - method.request.querystring.time:
                  Required: true
                  Caching: true
              - method.request.querystring.dtInSeconds:
                  Required: true
                  Caching: true

Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"